### ISSUE TITLE
[Question] Using replicated tables and carbonate

### ISSUE THREAD

**Issue by Hipska** [lomik/graphite-clickhouse#68]
Hi,

I'm trying to set up carbon-clickhouse, ClickHouse and graphite-clickhouse with replicated ClickHouse tables. Now my question is, if using carbonapi, should I configure all servers as endpoint, or only 1 (e.g. with VIP) and switch to another when the one is down?

**Comment by gpaggi** [comment]
Hi,

I configured mine with all hosts and lbMethod: roundrobin, see below:

```
upstreams:
    backendsv2:
      backends:
        -
          groupName: "clickhouse-DC1"
          protocol: "carbonapi_v2_pb"
          lbMethod: "roundrobin"
          keepAliveInterval: "10s"
          maxIdleConnsPerHost: 1000
          timeouts:
            find: "10s"
            render: "120s"
            connect: "200ms"
          servers:
            - "http://clickm001.node.consul:9095"
            - "http://clickm002.node.consul:9095"
            - "http://clickm003.node.consul:9095"
 ```
