### ISSUE TITLE
Grafana show only "Missing series in result" of graphite-clickhouse

### ISSUE THREAD

**Issue by yatsukav** [lomik/graphite-clickhouse#71]
I have next docker-compose file:
```
clickhouse:
  image: yandex/clickhouse-server:19.6.2.11
  volumes:
  - "./rollup.xml:/etc/clickhouse-server/config.d/rollup.xml"
  - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
  - "./data/clickhouse/data:/var/lib/clickhouse/data"
  - "./data/clickhouse/metadata:/var/lib/clickhouse/metadata"
carbon-clickhouse:
  image: lomik/carbon-clickhouse:v0.10.2
  volumes:
  - "./data/carbon-clickhouse:/data/carbon-clickhouse"
  - "./carbon-clickhouse.conf:/etc/carbon-clickhouse/carbon-clickhouse.conf"
  ports:
  - "2003:2003" # plain tcp
  - "2003:2003/udp" # plain udp
  - "2004:2004" # pickle
  - "2006:2006" # prometheus remote write
  links:
  - clickhouse
graphite-clickhouse:
  image: lomik/graphite-clickhouse:v0.11.1
  volumes:
  - "./rollup.xml:/etc/graphite-clickhouse/rollup.xml"
  - "./graphite-clickhouse.conf:/etc/graphite-clickhouse/graphite-clickhouse.conf"
  links:
  - clickhouse
grafana:
  image: grafana/grafana
  restart: always
  ports:
    - 3000:3000
  links:
    - graphite-clickhouse
```

I get error message on adding graphite data source:
<img width="461" alt="Screenshot 2020-01-02 at 03 01 33" src="https://user-images.githubusercontent.com/5247416/71647771-43e28e80-2d0c-11ea-9b2c-340a6eb31f5e.png">

And also on data exploring:
<img width="1243" alt="Screenshot 2020-01-02 at 03 02 51" src="https://user-images.githubusercontent.com/5247416/71647788-72606980-2d0c-11ea-9ad9-f6a425da4034.png">

I also put data in graphite via nc:
`echo "local.random.diceroll 4 `date +%s`" | nc 127.0.0.1 2003`

Graphite-web seems works fine. Is there any way to get the data in Grafana from graphite-clickhouse?
